server:
  port: ${SERVER_PORT:8083}
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/shopmart_payment?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:CHANGE_ME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
payment:
  simulate-failure: ${PAYMENT_SIMULATE_FAILURE:false}
  max-amount: ${PAYMENT_MAX_AMOUNT:80000000}
